# Generated by Django 4.0.1 on 2022-07-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_pedido',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
