# Generated by Django 4.0.1 on 2022-07-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_precio_alter_producto_precio_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
